import { useEffect, useState } from 'react'
import { Session } from '@supabase/supabase-js'
import { supabase } from '../lib/supabase'
import { Player } from '../types'

const ADMIN_EMAILS = ['hagai1973@gmail.com', 'hagaitregerman@gmail.com']


export interface SessionState {
  session: Session | null
  player: Player | null
  isAdmin: boolean
  needsOnboarding: boolean
  loading: boolean
  refetchPlayer: () => void
}

function isAutoGeneratedName(player: Player, session: Session): boolean {
  const provider = session.user.app_metadata?.provider
  if (provider === 'google') return false
  if (player.full_name?.startsWith('+')) return true
  if (player.email && player.full_name === player.email.split('@')[0]) return true
  if (player.full_name === 'New Player') return true
  return false
}

export function useSession(): SessionState {
  const [session, setSession] = useState<Session | null>(null)
  const [player, setPlayer] = useState<Player | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setSession(data.session)
      if (data.session) fetchPlayer(data.session)
      else setLoading(false)
    })

    const { data: listener } = supabase.auth.onAuthStateChange((_event, s) => {
      setSession(s)
      if (s) fetchPlayer(s)
      else { setPlayer(null); setLoading(false) }
    })

    return () => listener.subscription.unsubscribe()
  }, [])

  async function fetchPlayer(s: Session) {
    const uid = s.user.id

    let { data } = await supabase
      .from('players')
      .select('*')
      .eq('player_id', uid)
      .single()

    // Fallback: trigger may have failed — create the row via SECURITY DEFINER RPC
    if (!data) {
      const u = s.user
      const fullName =
        u.user_metadata?.full_name ??
        u.user_metadata?.name ??
        (u.email ? u.email.split('@')[0] : null) ??
        u.phone ??
        'New Player'

      await supabase.rpc('ensure_player_exists', {
        p_full_name: fullName,
        p_email:     u.email  ?? null,
        p_phone:     u.phone  ?? null,
      })

      const { data: created } = await supabase
        .from('players')
        .select('*')
        .eq('player_id', uid)
        .single()
      data = created
    }

    setPlayer(data ?? null)
    setLoading(false)
  }

  const needsOnboarding =
    !!session && !!player && isAutoGeneratedName(player, session)

  return {
    session,
    player,
    isAdmin: ADMIN_EMAILS.includes(session?.user?.email ?? ''),
    needsOnboarding,
    loading,
    refetchPlayer: () => { if (session) fetchPlayer(session) },
  }
}
